name: GitHub script test

on:
  workflow_call:

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo $JAVA_HOME_17_X64
        set JAVA_HOME=$JAVA_HOME_17_X64
        echo $JAVA_HOME
