name: GitHub script test

on:
  workflow_dispatch:
    inputs:
      build_status:
        required: true
        type: string

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(context.payload.inputs.build_status)
          //console.log(github)
