name: Notify Discord about build status

on:
  workflow_call:
    inputs:
      build_status:
        required: true
        type: string
    secrets:
      webhook_url:
        required: true

jobs:
  notify-discord:
    name: Notify Discord
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-tags: true
    - name: Get git commit description
      run: |
        echo $(git describe)
        echo $(git describe --tags)
        echo "GIT_COMMIT_DESC=$(git describe --tags)" >> $GITHUB_ENV
    - name: Create JSON embed for Discord
      id: create-json
      uses: actions/github-script@v6
      env:
        commit_desc: ${{ env.GIT_COMMIT_DESC }}
        build_status: ${{ inputs.build_status }}
        ref_type: ${{ github.ref_type }}
        ref_name: ${{ github.ref_name }}
      with:
        result-encoding: string
        script: |
          const script = require('./.github/workflows/js/notify-discord.js')
          return script({github, context})
          
    - name: Send notification
      run: |
        curl --http2-prior-knowledge --tlsv1.3 --false-start --tcp-fastopen --compressed -sS -m 10 -H "Content-Type: application/json" --request POST -d '${{ steps.create-json.outputs.result }}' ${{ env.DISCORD_WEBHOOK }}
      env:
        DISCORD_WEBHOOK: ${{ secrets.webhook_url }}
